routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/', 'HomeController@index')->name('home');

Route::group(['prefix' => 'administrator'], function () {


    Route::get('/login', 'Admin\LoginController@login')->name('admin.login');
    Route::post('/login', 'Admin\LoginController@postLogin')->name('admin.postLogin');

    // Password Reset Routes...

    Route::get('password/reset', 'Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('administrator.password.request');
    Route::post('password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('administrator.password.email');
    Route::get('password/reset/{token}', 'Admin\Auth\ResetPasswordController@showResetForm')->name('administrator.password.reset.token');
    Route::post('password/reset', 'Admin\Auth\ResetPasswordController@reset');

});

Route::group(['prefix' => 'administrator', 'middleware' => ['admin']], function () {

    Route::get('/', 'Admin\HomeController@index')->name('home');
    Route::get('/home', 'Admin\HomeController@index')->name('admin.home');


    // administrators --- Admin Panel users
    // add admin or some one who controll Or help for admin panel

    Route::resource('helpAdmin', 'Admin\HelpAdminController');
    Route::get('helpAdmin/{id}/delete', 'Admin\HelpAdminController@delete')->name('helpAdmin.delete');
    Route::post('helpAdmin/{id}/delete', 'Admin\HelpAdminController@deleteHelpAdmin')->name('helpAdmin.message.delete');
    Route::post('helpAdmin/{id}/suspend', 'Admin\HelpAdminController@suspendHelpAdmin')->name('helpAdmin.message.suspend');
    Route::get('user/{id}/delete', 'Admin\UsersController@delete')->name('user.for.delete');
    Route::post('user/suspend', 'Admin\HelpAdminController@suspend')->name('user.suspend');
    // Roles routes ..........
    Route::resource('roles', 'Admin\RolesController');
    Route::post('role/delete', 'Admin\RolesController@delete')->name('role.delete');


    Route::resource('users', 'Admin\UsersController');
    Route::post('accepted','Admin\UsersController@accpetedUser')->name('user.accepted');

    Route::get('settings/aboutus', 'Admin\SettingsController@aboutus')->name('settings.aboutus');
    Route::get('settings/taxs', 'Admin\SettingsController@taxs')->name('settings.taxs');
    Route::get('settings/terms', 'Admin\SettingsController@terms')->name('settings.terms');
    Route::get('settings/suspendElement', 'Admin\SettingsController@suspendElement')->name('settings.suspendElement');


    Route::get('/settings/app-general-settings', 'Admin\SettingsController@appGeneralSettings')->name('settings.app.general');
    Route::get('settings/contacts', 'Admin\SettingsController@contactus')->name('settings.contactus');


    Route::post('/settings', 'Admin\SettingsController@store')->name('administrator.settings.store');

    Route::post('contactus/reply/{id}', 'Admin\SupportsController@reply')->name('support.reply');
    Route::get('contactus', 'Admin\SupportsController@index')->name('support.index');
    Route::get('contactus/{id}', 'Admin\SupportsController@show')->name('support.show');
    Route::post('support/contact/delete', 'Admin\SupportsController@delete')->name('support.contact.delete');


    Route::resource('supports', 'Admin\SupportsController');
    Route::post('supports/delete', 'Admin\SupportsController@delete')->name('supports.delete');

    Route::resource('types', 'Admin\TypesSupportController');




    // -------------------------------------- categories .................
    Route::resource('categories', 'Admin\CategoriesController');
    Route::post('categories/delete', 'Admin\CategoriesController@delete')->name('categories.delete');
    Route::post('categories/suspend', 'Admin\CategoriesController@suspend')->name('categories.suspend');




    Route::resource('banks', 'Admin\BanksController');
    Route::post('bank/suspend', 'Admin\BanksController@suspend')->name('bank.suspend');



    Route::resource('videos', 'Admin\VideoController');
    Route::post('videos/suspend', 'Admin\VideoController@suspend')->name('videos.suspend');
    Route::post('videos/delete', 'Admin\VideoController@delete')->name('videos.delete');

    Route::post('/logout', 'Admin\LoginController@logout')->name('administrator.logout');

});

resources/views/admin/layouts/_partials/footer.blade.php
</div>
<!-- end container -->

<!-- Right Sidebar -->
<div class="side-bar right-bar">
    <a href="javascript:void(0);" class="right-bar-toggle">
        <i class="zmdi zmdi-close-circle-o"></i>
    </a>
    <h4 class="">Notifications</h4>
    <div class="notification-list nicescroll">
        <ul class="list-group list-no-border user-list">
            <li class="list-group-item">
                <a href="#" class="user-list-item">
                    <div class="avatar">
                        <img src="assets/images/users/avatar-2.jpg" alt="">
                    </div>
                    <div class="user-desc">
                        <span class="name">Michael Zenaty</span>
                        <span class="desc">There are new settings available</span>
                        <span class="time">2 hours ago</span>
                    </div>
                </a>
            </li>
            <li class="list-group-item">
                <a href="#" class="user-list-item">
                    <div class="icon bg-info">
                        <i class="zmdi zmdi-account"></i>
                    </div>
                    <div class="user-desc">
                        <span class="name">New Signup</span>
                        <span class="desc">There are new settings available</span>
                        <span class="time">5 hours ago</span>
                    </div>
                </a>
            </li>
            <li class="list-group-item">
                <a href="#" class="user-list-item">
                    <div class="icon bg-pink">
                        <i class="zmdi zmdi-comment"></i>
                    </div>
                    <div class="user-desc">
                        <span class="name">New Message received</span>
                        <span class="desc">There are new settings available</span>
                        <span class="time">1 day ago</span>
                    </div>
                </a>
            </li>
            <li class="list-group-item active">
                <a href="#" class="user-list-item">
                    <div class="avatar">
                        <img src="assets/images/users/avatar-3.jpg" alt="">
                    </div>
                    <div class="user-desc">
                        <span class="name">James Anderson</span>
                        <span class="desc">There are new settings available</span>
                        <span class="time">2 days ago</span>
                    </div>
                </a>
            </li>
            <li class="list-group-item active">
                <a href="#" class="user-list-item">
                    <div class="icon bg-warning">
                        <i class="zmdi zmdi-settings"></i>
                    </div>
                    <div class="user-desc">
                        <span class="name">Settings</span>
                        <span class="desc">There are new settings available</span>
                        <span class="time">1 day ago</span>
                    </div>
                </a>
            </li>

        </ul>
    </div>
</div>
<!-- /Right-bar -->
</div>

resources/views/admin/layouts/_partials/header.blade.php
<!-- Navigation Bar-->
<header id="topnav">

    <div class="topbar-main">
        <div class="container">

            <!-- LOGO -->
            <div class="topbar-left">
                {{--<a href="{{ route('admin.home') }}" class="logo" style="width: 150px;">--}}
                    {{--<img style="width: 100%" src="{{ request()->root() }}/public/assets/admin/images/logo.png"></a>--}}
            </div>
            <!-- End Logo container-->


            <div class="menu-extras">

                <ul class="nav navbar-nav navbar-right pull-right">
                    {{--<li>--}}
                    {{--<forsm role="search" class="navbar-left app-search pull-left hidden-xs">--}}
                    {{--<input type="text" placeholder="بحث ..." class="form-control">--}}
                    {{--<a href=""><i class="fa fa-search"></i></a>--}}
                    {{--</form>--}}
                    {{--</li>--}}

                    {{--<li>--}}
                        {{--<div class="notification-box">--}}
                            {{--<ul class="list-inline m-b-0">--}}
                                {{--<li>--}}
                                    {{--<a href="{{ route('notifications.index') }}" class="right-bar-toggle">--}}
                                    {{--<a href="#" class="right-bar-toggle">--}}
                                        {{--<i class="zmdi zmdi-notifications-none"></i>--}}
                                    {{--</a>--}}
                                    {{--<div class="noti-dot">--}}
                                        {{--<span class="dot"></span>--}}
                                        {{--<span class="pulse"></span>--}}
                                    {{--</div>--}}
                                {{--</li>--}}
                            {{--</ul>--}}
                        {{--</div>--}}
                    {{--</li>--}}

                    {{--<li class="dropdown">--}}
                        {{--<a href="" class="dropdown-toggle waves-effect waves-light profile " data-toggle="dropdown"--}}
                           {{--aria-expanded="true">--}}
                            {{--<img src="{{ request()->root() }}/public/assets/admin/images/saudi-arabia.png"--}}
                                 {{--alt="user-img"--}}
                                 {{--class="img-circle user-img">--}}
                        {{--</a>--}}

                        {{--<ul class="dropdown-menu">--}}

                            {{--<a href="#" class="dropdown-toggle" data-toggle="dropdown">--}}
                            {{--{{ app()->getLocale() }} <i class="fa fa-caret-down"></i>--}}
                            {{--</a>--}}

                            {{--@foreach (config('translatable.locales') as $lang => $language)--}}
                                {{--@if ($lang != app()->getLocale())--}}
                                    {{--<li>--}}
                                        {{--<a href="{{ route('lang.switch', $lang) }}">--}}
                                            {{--{{ $language }}--}}
                                        {{--</a>--}}
                                    {{--</li>--}}
                                {{--@endif--}}
                            {{--@endforeach--}}


                        {{--</ul>--}}
                    {{--</li>--}}

                    <li class="dropdown user-box">
                        <a href="" class="dropdown-toggle waves-effect waves-light profile " data-toggle="dropdown"
                           aria-expanded="true">
                            <img src="{{ $helper->getDefaultImage(auth()->user()->image, request()->root().'/public/assets/admin/images/default.png') }}"
                                 alt="user-img" class="img-circle user-img">
                        </a>

                        <ul class="dropdown-menu">
                            <li><a href="{{ route('helpAdmin.edit', auth()->user()->id)}}"><i
                                            class="ti-user m-r-5"></i>@lang('maincp.personal_page')</a></li>
{{--                            <!--<li><a href="{{ route('users.edit', auth()->id()) }}"><i class="ti-settings m-r-5"></i>-->--}}
                            <!--        @lang('global.settings')-->
                            <!--    </a>-->
                            <!--</li>-->
                            <li><a href="{{ route('administrator.logout') }}"
                                   onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                    <i class="ti-power-off m-r-5"></i>@lang('maincp.log_out')
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
                <div class="menu-item">
                    <!-- Mobile menu toggle-->
                    <a class="navbar-toggle">
                        <div class="lines">
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                    </a>
                    <!-- End mobile menu toggle-->
                </div>
            </div>

        </div>
    </div>

    <form id="logout-form" action="{{ route('administrator.logout') }}" method="POST"
          style="display: none;">
        {{ csrf_field() }}
    </form>

    <div class="navbar-custom">
        <div class="container">
            <div id="navigation">
                <!-- Navigation Menu-->
                <ul class="navigation-menu" style="    font-size: 14px;">
                    <li>
                        <a href="{{ route('admin.home') }}"><i class="zmdi zmdi-view-dashboard"></i>
                            <span> @lang('menu.home') </span> </a>
                    </li>

                    @can('companies_management')
                        <li class="has-submenu">
                            <a href="#"><i
                                        class="zmdi zmdi-accounts"></i><span>@lang('maincp.customer_management')   </span>
                            </a>
                            <ul class="submenu ">
                                <li>  <a href="{{ route('users.index') }}?type=clients">  @lang('trans.clients') </a>   </li>
                            </ul>
                        </li>

                    @endcan


                    @can('users_manage')
                    <li class="has-submenu">
                        <a href="#"><i class="zmdi zmdi-layers"></i><span>  @lang('trans.managers_ctrl_panel') </span>
                        </a>
                        <ul class="submenu ">
                            <li><a href="{{ route('helpAdmin.index') }}"> @lang('trans.managers_system')</a></li>
                            <li>
                                <a href="{{route('roles.index')}}">  @lang('trans.roles_and_permission')     </a>
                            </li>

                        </ul>
                    </li>
                    @endcan



                    @can('content_management')
                    <li class="has-submenu">
                        <a href="javascript:;">
                            <i class="zmdi zmdi-square-o"></i>
                            <span>  @lang('maincp.content_management')  </span>
                        </a>
                        <ul class="submenu ">

                            {{--<li><a href="{{ route('cities.index') }}?type=countery">الدول</a></li>--}}
                            {{--<li><a href="{{ route('cities.index') }}">@lang('trans.cities')</a></li>--}}
                            <li><a href="{{ route('banks.index') }}">@lang('trans.banks_accounts')</a></li>
                            <li><a href="{{ route('categories.index') }}">الأقسام الرئيسة</a></li>
                            {{--<li><a href="{{ route('categories.index') }}?type=subcategories">الأقسام الفرعية</a></li>--}}
                            <li><a href="{{ route('videos.index') }}">  الفديوهات</a></li>


                        </ul>
                    </li>

                    @endcan


                    @can('app_general_settings_management')


                    <li class="has-submenu">
                        <a href="#"><i class="zmdi zmdi-settings"></i><span>@lang('maincp.setting')<i
                                        class="fa fa-arrow-down visible-xs" aria-hidden="true"></i></span> </a>
                        <ul class="submenu">
                            <li><a href="{{ route('settings.contactus') }}">@lang('trans.general_setting_app')</a>    </li>

                            <li><a href="{{ route('settings.aboutus') }}">@lang('trans.about_app')</a>   </li>
                            <li><a href="{{ route('settings.terms') }}">@lang('trans.terms')</a></li>
                            <li><a href="{{ route('supports.index') }}">@lang('maincp.contact_us')</a></li>
                        </ul>
                    </li>
                    @endcan


                  @can('orders_management')

                    {{--<li class="has-submenu">--}}
                        {{--<a href="#"><i--}}
                                    {{--class="zmdi zmdi-border-all"></i><span>@lang('trans.orders_management')   </span>--}}
                        {{--</a>--}}
                        {{--<ul class="submenu ">--}}
                            {{--<li>--}}
{{--                                <a href="{{ route('reports.index') }}">         @lang('trans.bank_transfer_from_client')  </a>--}}
                                {{--<a href="{{ route('reports.index') }}">         @lang('trans.reports_orders')  </a>--}}
                            {{--</li>--}}

                        {{--</ul>--}}
                    {{--</li>--}}

                    @endcan



                    @can('reports_management')
                    <li class="has-submenu">
                        {{--<a href="#"><i class="zmdi zmdi-flag"></i><span>@lang('maincp.reports')</span> </a>--}}
                        <ul class="submenu">

                        </ul>
                    </li>
                    @endcan

                </ul>
                <!-- End navigation menu  -->
            </div>
        </div>
    </div>

</header>
<!-- End Navigation Bar-->


<div class="wrapper">
    <div class="container">

resources/views/admin/layouts/_partials/scripts.blade.php
<!-- jQuery  -->
<script src="{{ request()->root() }}/public/assets/admin/js/jquery.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/js/bootstrap-rtl.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/js/detect.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/js/fastclick.js"></script>

<script src="{{ request()->root() }}/public/assets/admin/js/jquery.slimscroll.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/js/jquery.blockUI.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/js/waves.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/js/wow.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/js/jquery.nicescroll.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/js/jquery.scrollTo.min.js"></script>

<!-- KNOB JS -->
<!--[if IE]>
<script type="text/javascript"
        src="{{ request()->root() }}/public/assets/admin/plugins/jquery-knob/excanvas.js"></script>
<![endif]-->
<script src="{{ request()->root() }}/public/assets/admin/plugins/jquery-knob/jquery.knob.js"></script>


<!-- responsive-table-->
<script src="{{ request()->root() }}/public/assets/admin/plugins/RWD-Table-Patterns/dist/js/rwd-table.min.js"
        type="text/javascript"></script>


<!-- Dashboard init -->
<script src="{{ request()->root() }}/public/assets/admin/pages/jquery.dashboard.js"></script>


<!-- file uploads js -->
<!--<script src="{{ request()->root() }}/public/assets/admin/plugins/fileuploads/js/dropify.min.js"></script>-->
<script src="https://jeremyfagis.github.io/dropify/dist/js/dropify.js"></script>
<!-- Validation js (Parsleyjs) -->
<script type="text/javascript"
        src="{{ request()->root() }}/public/assets/admin/plugins/parsleyjs/dist/parsley.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.js"></script>

<script src="{{ Request::root() }}/public/assets/admin/plugins/toastr/toastr.min.js"></script>

<script src="{{ request()->root() }}/public/assets/admin/plugins/switchery/switchery.min.js"></script>

<script type="text/javascript"
        src="{{ request()->root() }}/public/assets/admin/plugins/multiselect/js/jquery.multi-select.js"></script>

<script src="{{ Request::root() }}/public/assets/admin/plugins/ckeditor/ckeditor.js"></script>
<script src="{{ Request::root() }}/public/assets/admin/plugins/ckeditor/samples/js/sample.js"></script>

<!-- Sweet Alert js -->
<script src="{{ request()->root() }}/public/assets/admin/plugins/bootstrap-sweetalert/sweet-alert.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/pages/jquery.sweet-alert.init.js"></script>


<!-- App js -->
<script src="{{ request()->root() }}/public/assets/admin/js/jquery.core.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/js/jquery.app.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/js/validate-ar.js"></script>

<!-- Datatables-->
<script src="{{ request()->root() }}/public/assets/admin/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/plugins/datatables/dataTables.bootstrap.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/plugins/datatables/dataTables.buttons.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/plugins/datatables/buttons.bootstrap.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/plugins/datatables/jszip.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/plugins/datatables/pdfmake.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/plugins/datatables/vfs_fonts.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/plugins/datatables/buttons.html5.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/plugins/datatables/buttons.print.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/plugins/datatables/dataTables.fixedHeader.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/plugins/datatables/dataTables.keyTable.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/plugins/datatables/dataTables.responsive.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/plugins/datatables/responsive.bootstrap.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/plugins/datatables/dataTables.scroller.min.js"></script>

<!-- Datatable init js -->
<script src="{{ request()->root() }}/public/assets/admin/pages/datatables.init.js"></script>
{{--<script src="{{ request()->root() }}/public/assets/admin/js/examples.min.js"> </script>--}}

<!-- Toastr js -->
<script src="{{ request()->root() }}/public/assets/admin/plugins/toastr/toastr.min.js"></script>

<!-- Modal-Effect -->
<script src="{{ request()->root() }}/public/assets/admin/plugins/custombox/dist/custombox.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/plugins/custombox/dist/legacy.min.js"></script>


<script src="{{ request()->root() }}/public/assets/admin/plugins/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>


<script>



    $('body').delegate('.numbersOnly', 'keyup keypress', function (event) {

        var limit = $(this).attr('data-limit');
        var message = $(this).attr('data-message');
        var field = $(this).attr('name');

        if (!limit) {
            limit = 25;
        }

        if (this.value.length > limit) {
            $(this).css({
                'border': '1px solid red',
                'font-size': '14px',
                'color': 'red'
            });

            /****Not Work yet****/

            $('.' + field).css({
                'font-size': '12px'
            });

            $('.' + field).html(message);




        } else {
            $(this).removeAttr('style');
            $('.' + field).html('');

        }


        // if (!Number(this.value)) {
        //     this.value = this.value.replace(/[^0-9\.]/g, '');
        //     event.preventDefault();
        //     return false;
        // }


        if (this.value.length > limit) {
             
            this.value = this.value.replace(/[^0-9\.]/g, '');
            if(!Number(this.value)){
                $('.' + field).html(message);
            }
            event.preventDefault();
            return false;
        }

        this.value = this.value.replace(/[^0-9\.]/g, '');
    });
</script>

@yield('scripts')
<script>

    // Date Picker
    jQuery('.datepicker').datepicker();

    jQuery('.datepicker-autoclose').datepicker({
        autoclose: true,
        todayHighlight: true
    });


    initSample();

    //    TableManageButtons.init();


</script>

resources/views/admin/layouts/_partials/styles.blade.php
<!-- Custom box css -->
{{--<link href="{{ request()->root() }}/public/assets/admin/plugins/custombox/dist/custombox.min.css" rel="stylesheet">--}}

<link href="{{ request()->root() }}/public/assets/admin/plugins/RWD-Table-Patterns/dist/css/rwd-table.min.css" rel="stylesheet"
      type="text/css" media="screen">
<!-- form Uploads -->
<link href="{{ request()->root() }}/public/assets/admin/plugins/fileuploads/css/dropify.min.css" rel="stylesheet"
      type="text/css"/>
<!-- Sweet Alert css -->
<link href="{{ request()->root() }}/public/assets/admin/plugins/bootstrap-sweetalert/sweet-alert.css" rel="stylesheet"
      type="text/css"/>

<link href="{{ request()->root() }}/public/assets/admin/plugins/multiselect/css/multi-select.css" rel="stylesheet"
      type="text/css"/>

<link href="{{ request()->root() }}/public/assets/admin/plugins/datatables/jquery.dataTables.min.css" rel="stylesheet"
      type="text/css"/>
<link href="{{ request()->root() }}/public/assets/admin/plugins/datatables/buttons.bootstrap.min.css" rel="stylesheet"
      type="text/css"/>
<link href="{{ request()->root() }}/public/assets/admin/plugins/datatables/fixedHeader.bootstrap.min.css" rel="stylesheet"
      type="text/css"/>
<link href="{{ request()->root() }}/public/assets/admin/plugins/datatables/responsive.bootstrap.min.css" rel="stylesheet"
      type="text/css"/>
<link href="{{ request()->root() }}/public/assets/admin/plugins/datatables/scroller.bootstrap.min.css" rel="stylesheet"
      type="text/css"/>


<link href="{{ request()->root() }}/public/assets/admin/css-{{ config('app.locale') }}/bootstrap.min.css" rel="stylesheet"
      type="text/css"/>
<link href="{{ request()->root() }}/public/assets/admin/css-{{ config('app.locale') }}/core.css" rel="stylesheet"
      type="text/css"/>
<link href="{{ request()->root() }}/public/assets/admin/css-{{ config('app.locale') }}/components.css" rel="stylesheet"
      type="text/css"/>
<link href="{{ request()->root() }}/public/assets/admin/css-{{ config('app.locale') }}/icons.css" rel="stylesheet"
      type="text/css"/>
<link href="{{ request()->root() }}/public/assets/admin/css-{{ config('app.locale') }}/pages.css" rel="stylesheet"
      type="text/css"/>
<link href="{{ request()->root() }}/public/assets/admin/css-{{ config('app.locale') }}/menu.css" rel="stylesheet"
      type="text/css"/>
<link href="{{ request()->root() }}/public/assets/admin/css-{{ config('app.locale') }}/responsive.css" rel="stylesheet"
      type="text/css"/>

<link href="{{ request()->root() }}/public/assets/admin/plugins/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.css"
      rel="stylesheet"/>


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.css"/>

<link href="{{ Request::root() }}/public/assets/admin/plugins/toastr/toastr.css" rel="stylesheet" type="text/css"/>
<!-- Notification css (Toastr) -->
<link href="{{ Request::root() }}/public/assets/admin/plugins/toastr/toastr.min.css" rel="stylesheet" type="text/css"/>



{{--<link rel="stylesheet" href="{{ Request::root() }}/public/assets/admin/plugins/ckeditor/css/samples.css">--}}
<link href="{{ request()->root() }}/public/assets/admin/plugins/switchery/switchery.min.css" rel="stylesheet"/>

{{--<link href="{{ request()->root() }}/public/assets/admin/custom/css/custom.css" rel="stylesheet" type="text/css"/>--}}
{{--<link href="{{ request()->root() }}/public/assets/admin/custom/css/animate.css" rel="stylesheet" type="text/css"/>--}}
{{--<link href="{{ request()->root() }}/public/assets/admin/css/ionicons.min.css" rel="stylesheet">--}}
    <link href="{{ request()->root() }}/public/assets/admin/plugins/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css"
          rel="stylesheet">
<!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<!--<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>-->
<!--<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>-->
<![endif]-->