routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/', 'HomeController@index')->name('home');

Route::group(['prefix' => 'administrator'], function () {


    Route::get('/login', 'Admin\LoginController@login')->name('admin.login');
    Route::post('/login', 'Admin\LoginController@postLogin')->name('admin.postLogin');

    // Password Reset Routes...

    Route::get('password/reset', 'Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('administrator.password.request');
    Route::post('password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('administrator.password.email');
    Route::get('password/reset/{token}', 'Admin\Auth\ResetPasswordController@showResetForm')->name('administrator.password.reset.token');
    Route::post('password/reset', 'Admin\Auth\ResetPasswordController@reset');

});

Route::group(['prefix' => 'administrator', 'middleware' => ['admin']], function () {

    Route::get('/', 'Admin\HomeController@index')->name('home');
    Route::get('/home', 'Admin\HomeController@index')->name('admin.home');


    // administrators --- Admin Panel users
    // add admin or some one who controll Or help for admin panel

    Route::resource('helpAdmin', 'Admin\HelpAdminController');
    Route::get('helpAdmin/{id}/delete', 'Admin\HelpAdminController@delete')->name('helpAdmin.delete');
    Route::post('helpAdmin/{id}/delete', 'Admin\HelpAdminController@deleteHelpAdmin')->name('helpAdmin.message.delete');
    Route::post('helpAdmin/{id}/suspend', 'Admin\HelpAdminController@suspendHelpAdmin')->name('helpAdmin.message.suspend');
    Route::get('user/{id}/delete', 'Admin\UsersController@delete')->name('user.for.delete');
    Route::post('user/suspend', 'Admin\HelpAdminController@suspend')->name('user.suspend');
    // Roles routes ..........
    Route::resource('roles', 'Admin\RolesController');
    Route::post('role/delete', 'Admin\RolesController@delete')->name('role.delete');


    Route::resource('users', 'Admin\UsersController');
    Route::post('accepted','Admin\UsersController@accpetedUser')->name('user.accepted');

    Route::get('settings/aboutus', 'Admin\SettingsController@aboutus')->name('settings.aboutus');
    Route::get('settings/taxs', 'Admin\SettingsController@taxs')->name('settings.taxs');
    Route::get('settings/terms', 'Admin\SettingsController@terms')->name('settings.terms');
    Route::get('settings/suspendElement', 'Admin\SettingsController@suspendElement')->name('settings.suspendElement');


    Route::get('/settings/app-general-settings', 'Admin\SettingsController@appGeneralSettings')->name('settings.app.general');
    Route::get('settings/contacts', 'Admin\SettingsController@contactus')->name('settings.contactus');


    Route::post('/settings', 'Admin\SettingsController@store')->name('administrator.settings.store');

    Route::post('contactus/reply/{id}', 'Admin\SupportsController@reply')->name('support.reply');
    Route::get('contactus', 'Admin\SupportsController@index')->name('support.index');
    Route::get('contactus/{id}', 'Admin\SupportsController@show')->name('support.show');
    Route::post('support/contact/delete', 'Admin\SupportsController@delete')->name('support.contact.delete');


    Route::resource('supports', 'Admin\SupportsController');
    Route::post('supports/delete', 'Admin\SupportsController@delete')->name('supports.delete');

    Route::resource('types', 'Admin\TypesSupportController');




    // -------------------------------------- categories .................
    Route::resource('categories', 'Admin\CategoriesController');
    Route::post('categories/delete', 'Admin\CategoriesController@delete')->name('categories.delete');
    Route::post('categories/suspend', 'Admin\CategoriesController@suspend')->name('categories.suspend');




    Route::resource('banks', 'Admin\BanksController');
    Route::post('bank/suspend', 'Admin\BanksController@suspend')->name('bank.suspend');



    Route::resource('videos', 'Admin\VideoController');
    Route::post('videos/suspend', 'Admin\VideoController@suspend')->name('videos.suspend');
    Route::post('videos/delete', 'Admin\VideoController@delete')->name('videos.delete');

    Route::post('/logout', 'Admin\LoginController@logout')->name('administrator.logout');

});

app/Models/Support.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Support extends Model
{

    public function user()
    {
        return $this->belongsTo(User::class);
    }


    public function children()
    {
       return  $this->hasMany(Support::class, 'parent_id');
    }
       
       public function type()
       {
	    return $this->belongsTo(TypesSupport::class);
       }

}

app/Http/Controllers/Admin/SupportsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Device;
use App\Libraries\Main;
use App\Libraries\PushNotification;
use App\Message;
use App\Notifications;
use App\Models\Support;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Gate;
use Carbon\Carbon;
use App\Models\Notification;

class SupportsController extends Controller
{


    public $push;
    public $main;

    public function __construct(PushNotification $push, Main $main)
    {

        $this->push = $push;
        $this->main = $main;

    }


    public function index()
    {
        $supports = Support::whereParentId(0)->get();
        return view('admin.supports.index')->with(compact('supports'));
    }

    public function show($id)
    {

        $message = Support::with('user')->whereId($id)->first();
        $message->is_read = 1;
        $message->save();

        return view('admin.supports.show')->with(compact('message'));
    }

    public function reply(Request $request, $id)
    {


        $message = Support::findOrFail($id);
        
        
        $sender = User::whereId($message->user_id)->first();
        


        if ($request->message == '') {
            return response()->json([
                'status' => false,
                'message' => 'من فضلك ادخل بيانات الرسالة ثم اعد الإرسال'
            ]);
        }


        if ($request->message == '') {
            return response()->json([
                'status' => false,
                'message' => 'من فضلك ادخل نص الرد '
            ]);
        }


        $support = new Support;
        $support->message = $request->message;

        $support->type_id = 1;

        if ($request->email)
            $support->email = $request->email;
        $support->user_id = auth()->id();


        $support->parent_id = $id;

        if ($support->save()) {
        
//             $data = array(
//                "user_id" => $sender->id,
//                'title' => "رد على الرسالة",
//                'body' => $support->message,
//                'order_id' => null,
//                'type' => 6,
//                'sender_id' => auth()->id(),
//                'created_at' => Carbon::now(),
//                'updated_at' => Carbon::now()
//            );

//            $this->main->insertData(Notification::class, $data);
//
//            $senderDevicesAndroid =  $sender->devices()->where('device_type', 'android')->pluck('device');
//            $senderDevicesIos =  $sender->devices()->where('device_type', 'ios')->pluck('device');

//            $this->push->sendPushNotification($senderDevicesAndroid, $senderDevicesIos, $data['title'], $data['body'], $data);
            

            $support->created = $support->created_at->format(' Y/m/d  ||  H:i:s ');
            return response()->json([
                'status' => true,
                'message' => __('web.reply_sent_successfully'),
                'data' => $support

            ], 200);
        } else {
            return response()->json([
                'status' => false,
            ]);
        }
    }

    
    public function delete(Request $request)
    {


        if (!Gate::allows('users_manage')) {
            return abort(401);
        }


        $model = Support::findOrFail($request->id);

        if ($model->children->count() > 0)
            $model->children()->delete();


        if ($model->delete()) {
            return response()->json([
                'status' => true,
                'data' => [
                    'id' => $request->id
                ]
            ]);
        }


    }

}

resources/views/admin/supports/create.blade.php
@extends('admin.layouts.master')

@section('content')

    <div id="messageError"></div>
    <form data-parsley-validate novalidate method="POST" action="{{ route('categories.store') }}"
          enctype="multipart/form-data">
    {{ csrf_field() }}
    <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12">
                <div class="btn-group pull-right m-t-15">


                    <button type="button" class="btn btn-custom dropdown-toggle waves-effect waves-light"
                            data-toggle="dropdown" aria-expanded="false">Settings <span class="m-l-5"><i
                                    class="fa fa-cog"></i></span>
                    </button>


                </div>
                <h4 class="page-title">أنواع المنشأت</h4>
            </div>
        </div>


        <div class="row">
            <div class="col-lg-8">
                <div class="card-box">
                    <h4 class="header-title m-t-0 m-b-30">إضافة نوع جديد</h4>

                    <div class="form-group">
                        <label for="userName">الاسم*</label>
                        <input type="text" name="name" parsley-trigger="change" required
                               placeholder="ادخل الاسم لنوع المنشأة..." class="form-control"
                               id="userName"
                               data-parsley-required-message="هذا الحقل إلزامي">
                    </div>


                    <div class="form-group">
                        <label for="pass1">الرئيسي*</label>
                        <select class="form-control select2" name="parent">
                            <option value="">الرئيسيى</option>
                            @foreach($cats as $category)
                                @if(old('parent') == $category->id)
                                    <option value="{{ $category->id }}" selected>{{ $category->name }}</option>
                                @else
                                    <option value="{{ $category->id }}">{{ $category->name }}</option>

                                @endif
                            @endforeach

                        </select>
                    </div>


                    <div class="form-group text-right m-b-0 ">
                        <button class="btn btn-primary waves-effect waves-light m-t-20" type="submit"> حفظ البيانات
                        </button>
                        <button onclick="window.history.back();return false;"
                                class="btn btn-default waves-effect waves-light m-l-5 m-t-20"> إلغاء
                        </button>
                    </div>

                </div>
            </div><!-- end col -->

            <div class="col-lg-4">
                <div class="card-box" style="overflow: hidden;">

                    <h4 class="header-title m-t-0 m-b-30">الصورة</h4>

                    <div class="form-group">
                        <input type="file" name="image" class="dropify" data-max-file-size="6M"/>
                    </div>

                </div>
            </div><!-- end col -->
        </div>
        <!-- end row -->
    </form>


@endsection


@section('scripts')
    {{--<script type="text/javascript">--}}

    {{--$('form').on('submit', function (e) {--}}
    {{--e.preventDefault();--}}
    {{--var formData = new FormData(this);--}}
    {{--$.ajax({--}}
    {{--type: 'POST',--}}
    {{--url: $(this).attr('action'),--}}
    {{--data: formData,--}}
    {{--cache: false,--}}
    {{--contentType: false,--}}
    {{--processData: false,--}}
    {{--success: function (data) {--}}

    {{--//  $('#messageError').html(data.message);--}}

    {{--var shortCutFunction = 'success';--}}
    {{--var msg = data.message;--}}
    {{--var title = 'نجاح';--}}
    {{--toastr.options = {--}}
    {{--positionClass: 'toast-top-left',--}}
    {{--onclick: null--}}
    {{--};--}}
    {{--var $toast = toastr[shortCutFunction](msg, title); // Wire up an event handler to a button in the toast, if it exists--}}
    {{--$toastlast = $toast;--}}
    {{--setTimeout(function () {--}}
    {{--window.location.href = '{{ route('categories.index') }}';--}}
    {{--}, 3000);--}}
    {{--},--}}
    {{--error: function (data) {--}}

    {{--}--}}
    {{--});--}}
    {{--});--}}

    {{--</script>--}}
@endsection

resources/views/admin/supports/edit.blade.php
@extends('admin.layouts.master')

@section('content')

    <div id="messageError"></div>
    <form data-parsley-validate novalidate method="POST" action="{{ route('categories.update', $category->id) }}"
          enctype="multipart/form-data">
    {{ csrf_field() }}
    {{ method_field('PUT') }}
    <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12">
                <div class="btn-group pull-right m-t-15">


                    <button type="button" class="btn btn-custom dropdown-toggle waves-effect waves-light"
                            data-toggle="dropdown" aria-expanded="false">Settings <span class="m-l-5"><i
                                    class="fa fa-cog"></i></span>
                    </button>


                </div>
                <h4 class="page-title">أنواع المنشأت</h4>
            </div>
        </div>


        <div class="row">
            <div class="col-lg-8">
                <div class="card-box">
                    <h4 class="header-title m-t-0 m-b-30">إضافة نوع جديد</h4>

                    <div class="form-group">
                        <label for="userName">الاسم*</label>
                        <input type="text" value="{{ $category->name or old('name') }}" name="name"
                               parsley-trigger="change" required
                               placeholder="ادخل الاسم لنوع المنشأة..." class="form-control"
                               id="userName"
                               data-parsley-required-message="هذا الحقل إلزامي">
                    </div>


                    <div class="form-group">
                        <label for="pass1">الرئيسي*</label>
                        <select class="form-control select2" name="parent">
                            <option value="">الرئيسيى</option>
                            @foreach($cats as $cat)
                                <option value="{{ $cat->id }}"
                                        @if($cat->id == $category->parent_id) selected @endif>{{ $cat->name }}</option>
                            @endforeach
                        </select>
                    </div>


                    <div class="form-group text-right m-b-0">
                        <button class="btn btn-primary waves-effect waves-light" type="submit"> حفظ البيانات
                        </button>
                        <button onclick="window.history.back();return false;"
                                class="btn btn-default waves-effect waves-light m-l-5"> إلغاء
                        </button>
                    </div>

                </div>
            </div><!-- end col -->

            <div class="col-lg-4">
                <div class="card-box" style="overflow: hidden;">

                    <h4 class="header-title m-t-0 m-b-30">الصورة</h4>

                    <div class="form-group">
                        <input type="file" name="image" data-default-file="{{ $category->image }}" class="dropify"
                               data-max-file-size="6M"/>
                    </div>

                </div>
            </div><!-- end col -->
        </div>
        <!-- end row -->
    </form>


@endsection

resources/views/admin/supports/load.blade.php
<div id="load">


    <table class="table m-0">
        <thead>
        <tr>
            <th>
                <input type="checkbox"/>
            </th>
            <th>صورة المنشأة</th>
            <th>اسم المنشأة</th>
            <th>نوع المنشأة</th>
            <th>تاريخ الانشاء</th>
            <th>الخيارات</th>

        </tr>
        </thead>
        <tbody>


        @foreach($categories as $category)
            <tr>
                <td><input type="checkbox"/></td>

                <td style="width: 10%;">


                    <a data-fancybox="gallery"
                       href="{{ $helper->getDefaultImage($category->image, request()->root().'/assets/admin/custom/images/default.png') }}">
                        <img style="width: 50%; border-radius: 50%; height: 49px;"
                             src="{{ $helper->getDefaultImage($category->image, request()->root().'/assets/admin/custom/images/default.png') }}"/>

                    </a>

                </td>
                <td>{{ $category->name }}</td>
                <td>{{ $category->created_at }}</td>
                <td>{{ $category->updated_at }}</td>
                <td>
                    <button class="btn btn-icon btn-trans btn-sm waves-effect waves-light btn-danger m-b-5">
                        <i class="fa fa-remove"></i>
                    </button>
                    <button class="btn btn-icon btn-sm waves-effect btn-default m-b-5">
                        <i class="fa fa-edit"></i>
                    </button>
                </td>
            </tr>
        @endforeach


        </tbody>
    </table>

    {{--@foreach($categories as $category)--}}


    {{--<div style="display: block;">--}}


    {{--<a data-fancybox="gallery"--}}
    {{--href="{{ $helper->getDefaultImage($category->image, request()->root().'/assets/admin/custom/images/default.png') }}">--}}
    {{--<img style="width: 20%;"--}}
    {{--src="{{ $helper->getDefaultImage($category->image, request()->root().'/assets/admin/custom/images/default.png') }}"/>--}}

    {{--</a>--}}





    {{--{{ $category->name }}--}}

    {{--{{ $category->created_at }}--}}

    {{--{{ $category->updated_at }}--}}




    {{--<button class="btn btn-icon btn-trans btn-sm waves-effect waves-light btn-danger m-b-5">--}}
    {{--<i class="fa fa-remove"></i>--}}
    {{--</button>--}}
    {{--<button class="btn btn-icon btn-sm waves-effect btn-default m-b-5">--}}
    {{--<i class="fa fa-edit"></i>--}}
    {{--</button>--}}


    {{--</div>--}}
    {{--@endforeach--}}
</div>


{{ $categories->links() }}

resources/views/admin/supports/show.blade.php
@extends('admin.layouts.master')

@section('title' , __('maincp.message_details'))

@section('content')

    <!-- Page-Title -->
    <div class="row">
        <div class="col-sm-12">
            <div class="btn-group pull-right m-t-15">
                <a href="{{ route('support.index') }}"
                   class="btn btn-custom  waves-effect waves-light"> @lang('maincp.back')<span class="m-l-5"><i
                                class="fa fa-reply"></i></span>
                </a>
            </div>
            <h4 class="page-title">@lang('maincp.message_details') </h4>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 col-xs-12">
            <div class="bg-picture card-box">
                <div class="profile-info-name">
                    <div class="profile-info-detail">


                        @if($message->user_id != "")

                            <h3
                                        class="m-t-0 m-b-10">{{($message->user)?($message->user->name)?: $message->user->username :'' }}</h3>

                        @else

                            <h3 c lass="m-t-0 m-b-10">{{ $message->name }}</h3>


                        @endif



                        @if($message->type == 1)
                            <span class="label label-danger">@lang('maincp.complaints')</span>
                        @elseif($message->type == 2)
                            <span class="label label-success">@lang('maincp.suggestions')</span>
                        @else
                            <span class="label label-inverse">@lang('maincp.others')</span>

                        @endif
                        <p class="m-t-10">{{ $message->message }}</p>
                        <p>
                            <i class="fa fa-calendar"></i> {{ $message->created_at->format('Y/m/d  ||  H:i:s ') }}
                            <i class="fa fa-envelope"></i> @if($message->user) {{ $message->user->email }} @endif
                        </p>
                        <p>
                            <i class="fa fa-phone"></i> @if($message->user_id != "") {{ $message->user->phone }} @else {{ $message->phone }} @endif
                        </p>


                    </div>


                    <div id="supportReplies">


                        @foreach(App\Models\Support::orderBy('created_at', 'desc')->whereParentId($message->id)->get() as $row)
                            <div class="card bg-lightdark p-20 m-t-20">
                                {{ $row->message }}
                            </div>
                            <p class="m-t-10">

                            <div class="row">

                                <div class="col-md-6">
                                    <i class="fa fa-calendar"></i> {{ $row->created_at->format('Y/m/d  ||  H:i:s ') }}
                                </div>
                            </div>
                        @endforeach

                    </div>

                    <div class="clearfix"></div>
                </div>
            </div>
            <!--/ meta -->


        </div>
        <div class="col-md-6 col-xs-12">
            <form method="post" action="{{ route('support.reply',$message->id) }}" class="card-box">
                            <span class="input-icon icon-right">
                                <textarea rows="5" class="form-control" name="message" required
                                          placeholder="@lang('maincp.reply_to_current_message')   ..."
                                          data-parsley-error-message="@lang('trans.message_required') "></textarea>
                            </span>


                <div class="p-t-10">
                    <button class="btn btn-sm btn-primary waves-effect waves-light">@lang('maincp.send')
                        <i style="display: none;" id="spinnerDiv" class="fa fa-spinner fa-spin"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>



@endsection


@section('scripts')


    <script>


        @if(session()->has('success'))

        setTimeout(function () {
            showMessage('{{ session()->get('success') }}');
        }, 3000);


        @endif



        $('body').on('click', '.removeElement', function () {
            var id = $(this).attr('data-id');
            var $tr = $(this).closest($('#elementRow' + id).parent().parent());
            swal({
                title: "هل انت متأكد؟",
                text: "يمكنك استرجاع المحذوفات مرة اخرى لا تقلق.",
                type: "error",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "موافق",
                cancelButtonText: "إلغاء",
                confirmButtonClass: 'btn-danger waves-effect waves-light',
                closeOnConfirm: true,
                closeOnCancel: true,
            }, function (isConfirm) {
                if (isConfirm) {
                    $.ajax({
                        type: 'POST',
                        url: '{{ route('support.contact.delete') }}',
                        data: {id: id},
                        dataType: 'json',
                        success: function (data) {
                            if (data) {
                                var shortCutFunction = 'success';
                                var msg = 'لقد تمت عملية الحذف بنجاح.';
                                var title = data.title;
                                toastr.options = {
                                    positionClass: 'toast-top-center',
                                    onclick: null,
                                    showMethod: 'slideDown',
                                    hideMethod: "slideUp",
                                };
                                var $toast = toastr[shortCutFunction](msg, title); // Wire up an event handler to a button in the toast, if it exists
                                $toastlast = $toast;
                            }

                            $tr.find('td').fadeOut(1000, function () {
                                $tr.remove();
                            });
                        }
                    });
                } else {

                    swal({
                        title: "تم الالغاء",
                        text: "انت لغيت عملية الحذف تقدر تحاول فى اى وقت :)",
                        type: "error",
                        showCancelButton: false,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "موافق",
                        confirmButtonClass: 'btn-info waves-effect waves-light',
                        closeOnConfirm: false,
                        closeOnCancel: false

                    });

                }
            });
        });


        function showMessage(message) {

            var shortCutFunction = 'success';
            var msg = message;
            var title = 'نجاح!';
            toastr.options = {
                positionClass: 'toast-top-center',
                onclick: null,
                showMethod: 'slideDown',
                hideMethod: "slideUp",
            };
            var $toast = toastr[shortCutFunction](msg, title);
            // Wire up an event handler to a button in the toast, if it exists
            $toastlast = $toast;


        }


    </script>

    <script type="text/javascript">

        $('form').on('submit', function (e) {
            e.preventDefault();
            var formData = new FormData(this);


            $('#spinnerDiv').show();

            $.ajax({
                type: 'POST',
                url: $(this).attr('action'),
                data: formData,
                cache: false,
                contentType: false,
                processData: false,
                success: function (data) {

                    if (data.status == true) {


                        console.log(data.data.message);
                        $('#spinnerDiv').hide();
                        $("[name='message']").val('');
                        $("[name='reply_type']").val('');


                        if (data.data.reply_type == 0)
                            typeReply = " إرسال عبر رسائل (SMS) "
                        else
                            typeReply = " إرسال عبر البريد الإلكتروني "

                        var div = "<div class='card bg-lightdark p-20 m-t-20 show' >"
                            + data.data.message
                            + "</div>"
                            + "<p class=\"m-t-10\">"
                            + "<div class='row'>"
                            + "<div class='col-md-6'>"
                            + "<i class='fa fa-calendar'></i> " + data.data.created
                            + "</div>"
                            + "</div>"
                            + "</div>"


                        $('#supportReplies').prepend(div);

                        var shortCutFunction = 'success';
                        var msg = data.message;
                        var title = 'نجاح';
                        toastr.options = {
                            positionClass: 'toast-top-left',
                            onclick: null
                        };
                        var $toast = toastr[shortCutFunction](msg, title); // Wire up an event handler to a button in the toast, if it exists
                        $toastlast = $toast;

                    }

                    if (data.status == false) {

                        // var shortCutFunction = 'error';
                        // var msg = data.message;
                        // var title = 'نجاح';
                        // toastr.options = {
                        //     positionClass: 'toast-top-left',
                        //     onclick: null
                        // };
                        // var $toast = toastr[shortCutFunction](msg, title); // Wire up an event handler to a button in the toast, if it exists
                        // $toastlast = $toast;


                        setTimeout(function () {
                            $('#spinnerDiv').hide();
                        }, 1000);
                    }




                    {{--setTimeout(function () {--}}
                    {{--window.location.href = '{{ route('categories.index') }}';--}}
                    {{--}, 3000);--}}
                },
                error: function (data) {
                    $('#spinnerDiv').hide();
                }
            });
        });

    </script>

@endsection