routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/', 'HomeController@index')->name('home');

Route::group(['prefix' => 'administrator'], function () {


    Route::get('/login', 'Admin\LoginController@login')->name('admin.login');
    Route::post('/login', 'Admin\LoginController@postLogin')->name('admin.postLogin');

    // Password Reset Routes...

    Route::get('password/reset', 'Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('administrator.password.request');
    Route::post('password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('administrator.password.email');
    Route::get('password/reset/{token}', 'Admin\Auth\ResetPasswordController@showResetForm')->name('administrator.password.reset.token');
    Route::post('password/reset', 'Admin\Auth\ResetPasswordController@reset');

});

Route::group(['prefix' => 'administrator', 'middleware' => ['admin']], function () {

    Route::get('/', 'Admin\HomeController@index')->name('home');
    Route::get('/home', 'Admin\HomeController@index')->name('admin.home');


    // administrators --- Admin Panel users
    // add admin or some one who controll Or help for admin panel

    Route::resource('helpAdmin', 'Admin\HelpAdminController');
    Route::get('helpAdmin/{id}/delete', 'Admin\HelpAdminController@delete')->name('helpAdmin.delete');
    Route::post('helpAdmin/{id}/delete', 'Admin\HelpAdminController@deleteHelpAdmin')->name('helpAdmin.message.delete');
    Route::post('helpAdmin/{id}/suspend', 'Admin\HelpAdminController@suspendHelpAdmin')->name('helpAdmin.message.suspend');
    Route::get('user/{id}/delete', 'Admin\UsersController@delete')->name('user.for.delete');
    Route::post('user/suspend', 'Admin\HelpAdminController@suspend')->name('user.suspend');
    // Roles routes ..........
    Route::resource('roles', 'Admin\RolesController');
    Route::post('role/delete', 'Admin\RolesController@delete')->name('role.delete');


    Route::resource('users', 'Admin\UsersController');
    Route::post('accepted','Admin\UsersController@accpetedUser')->name('user.accepted');

    Route::get('settings/aboutus', 'Admin\SettingsController@aboutus')->name('settings.aboutus');
    Route::get('settings/taxs', 'Admin\SettingsController@taxs')->name('settings.taxs');
    Route::get('settings/terms', 'Admin\SettingsController@terms')->name('settings.terms');
    Route::get('settings/suspendElement', 'Admin\SettingsController@suspendElement')->name('settings.suspendElement');


    Route::get('/settings/app-general-settings', 'Admin\SettingsController@appGeneralSettings')->name('settings.app.general');
    Route::get('settings/contacts', 'Admin\SettingsController@contactus')->name('settings.contactus');


    Route::post('/settings', 'Admin\SettingsController@store')->name('administrator.settings.store');

    Route::post('contactus/reply/{id}', 'Admin\SupportsController@reply')->name('support.reply');
    Route::get('contactus', 'Admin\SupportsController@index')->name('support.index');
    Route::get('contactus/{id}', 'Admin\SupportsController@show')->name('support.show');
    Route::post('support/contact/delete', 'Admin\SupportsController@delete')->name('support.contact.delete');


    Route::resource('supports', 'Admin\SupportsController');
    Route::post('supports/delete', 'Admin\SupportsController@delete')->name('supports.delete');

    Route::resource('types', 'Admin\TypesSupportController');




    // -------------------------------------- categories .................
    Route::resource('categories', 'Admin\CategoriesController');
    Route::post('categories/delete', 'Admin\CategoriesController@delete')->name('categories.delete');
    Route::post('categories/suspend', 'Admin\CategoriesController@suspend')->name('categories.suspend');




    Route::resource('banks', 'Admin\BanksController');
    Route::post('bank/suspend', 'Admin\BanksController@suspend')->name('bank.suspend');



    Route::resource('videos', 'Admin\VideoController');
    Route::post('videos/suspend', 'Admin\VideoController@suspend')->name('videos.suspend');
    Route::post('videos/delete', 'Admin\VideoController@delete')->name('videos.delete');

    Route::post('/logout', 'Admin\LoginController@logout')->name('administrator.logout');

});

app/Models/Video.php
<?php

namespace App\Models;

use App\User;
use Dimsav\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;
use willvincent\Rateable\Rateable;

class Video extends Model
{
    use Rateable;
    use Translatable;

    public $translatedAttributes = ['name', 'description'];

    protected $fillable = ['name', 'description' ,'category_id','uploads','is_suspend','message'];

    protected $casts = [ 'uploads' => 'array'];


    public function category() {
        return $this->belongsTo(Category::class);
    }



    public function user() {
        return $this->belongsTo(User::class);
    }


    public function ratings()
    {
        return $this->morphMany('willvincent\Rateable\Rating', 'rateable');
    }

    public function views() {
        return $this->hasMany(View::class);
    }


}

app/Http/Controllers/Admin/VideoController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Category;
use App\Models\Setting;
use App\Models\Upload;
use App\Models\Video;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use getID3;
use UploadImage;
use Validator;
class VideoController extends Controller
{

    public $public_path;

    function __construct()
    {
        $this->public_path = 'files/videos/';

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $videos = Video::latest()->get();

        return view('admin.videos.index',compact('videos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $cats = Category::whereParentId(0)->where('is_suspend',0)->get();

        return view('admin.videos.create' , compact('cats'));
    }

    public function store(Request $request)
    {

        $validator = Validator::make($request->all(), [
            'file' => 'required|mimes:mp4,ogx,oga,ogv,ogg,webm',
        ]);

        if ($validator->fails()) {
            $valErrors = $validator->messages();
            return response()->json([  'status' => 422 ,'message' => $valErrors]);
        }



//        $ids =  Video::where('user_id',Auth::id())->pluck('uploads');
//
//        $MB_User_Have = Upload::whereIn('id', $ids)->pluck('fileSize')->sum();
//
//        $max_upload =  Setting::whereKey('mx_upload_video')->first()? value('body') : null;
//
//        if ($max_upload){
//            $getID3 = new getID3();
//            $video_file = $getID3->analyze($_FILES['file']['tmp_name']);
//
//
//            $userUploadAndMaxHave =  number_format($video_file['filesize'] / 1048576,0) + $MB_User_Have;
//
//            if ($userUploadAndMaxHave > $max_upload) {
//                $valErrors = ['file' => trans('global.permission_max_upload')];
//                return response()->json([  'status' => 422 ,'message' => $valErrors]);
//            }
//        }


        DB::transaction(function ( ) use ($request) {

            DB::beginTransaction();

            $video = new Video();
            $video->user_id = \Auth::id();
            $video->{'name:ar'} = $request->name_ar;
            $video->{'name:en'} = $request->name_en;
            $video->{'description:ar'} = $request->desc_ar;
            $video->{'description:en'} = $request->desc_en;
            $video->category_id = $request->categoryId;
            $video->save();

            $getID3 = new getID3();
            $video_file = $getID3->analyze($_FILES['file']['tmp_name']);
            $myUpload = explode('.', $_FILES['file']["name"]);
            $nameOfVideo = current($myUpload);

            $upload = new Upload();
            $upload->url = $request->root() . '/public/' . $this->public_path . UploadImage::uploadVideo($request, 'file','/files/videos/');
            $upload->fileExtension = $video_file['fileformat'];
            $upload->fileType = $video_file['mime_type'];
            $upload->fileSize = number_format($video_file['filesize'] / 1048576,0);
            $upload->fileQuality = $video_file['video']['resolution_y'];
            $upload->time = $video_file['playtime_string'];
            $upload->fileDescription = $nameOfVideo;
            $upload->save();

            $video->update(['uploads' => (array) json_encode(  $upload->id)  ]);

            if( !$video || !$upload )
            {
                DB::rollBack();

            } else {

                DB::commit();

            }

        });

        return response()->json([  'status' => 200 ,'url' => route('videos.index')]);

    }

    private function uploadVideoFile($request){
        $myUpload = explode('.', $_FILES["file"]["name"]);
        $fileName = current($myUpload);
        $extension = end($myUpload);
        $file_size = number_format($request->file('file')->getSize() / 1048576,0);

        $upload = new Upload();
        $upload->url = $request->root() . '/public/' . $this->public_path . UploadImage::uploadVideo($request, 'file','/files/videos/');
        $upload->fileExtension = $extension;
        $upload->fileType = $_FILES["file"]["type"] ;
        $upload->fileSize = $file_size ;
        $upload->fileQuality = $file_size ;
        $upload->fileDescription = $fileName ;
        $upload->save();

    }




    public function show($id)
    {
        $video = Video::with('user','category')->findOrFail($id);
        $video->uploads =   $video->uploads ?$this->getFileUploads( $video->uploads) : null;

        return view('admin.videos.show' , compact('video'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $video = Video::with('user','category')->findOrFail($id);
        $video->uploads =   $video->uploads ?$this->getFileUploads( $video->uploads) : null;

        $cats = Category::whereParentId(0)->where('is_suspend',0)->get();

        return view('admin.videos.edit' , compact('video','cats'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $video = Video::findOrFail($id);
        $video->user_id = \Auth::id();
        $video->{'name:ar'} = $request->name_ar;
        $video->{'name:en'} = $request->name_en;
        $video->{'description:ar'} = $request->desc_ar;
        $video->{'description:en'} = $request->desc_en;
        $video->category_id = $request->categoryId;
        $video->save();

        if ($request->file){
            $getID3 = new getID3();
            $video_file = $getID3->analyze($_FILES['file']['tmp_name']);
            $myUpload = explode('.', $_FILES['file']["name"]);
            $nameOfVideo = current($myUpload);

            $upload = new Upload();
            $upload->url = $request->root() . '/public/' . $this->public_path . UploadImage::uploadVideo($request, 'file','/files/videos/');
            $upload->fileExtension = $video_file['fileformat'];
            $upload->fileType = $video_file['mime_type'];
            $upload->fileSize = number_format($video_file['filesize'] / 1048576,0);
            $upload->fileQuality = $video_file['video']['resolution_y'];
            $upload->fileDescription = $nameOfVideo;
            $upload->save();

            $video->update(['uploads' => (array) json_encode(  $upload->id)  ]);

        }

        return response()->json([  'status' => 200 ,'url' => route('videos.index')]);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


    public function suspend(Request $request)
    {
        $model = Video::findOrFail($request->id);
        $model->is_suspend = $request->type;
        if ($request->type == 1) {
            $message = "لقد تم حظر  بنجاح";

        } else {
            $message = "لقد تم فك الحظر بنجاح";
        }

        if ($model->save()) {
            return response()->json([
                'status' => true,
                'message' => $message,
                'id' => $request->id,
                'type' => $request->type

            ]);
        }

    }

    public function delete(Request $request)
    {

        $video = Video::findOrFail($request->id);




        if ($video) {
            $video->delete();
            $video->deleteTranslations();

            return response()->json([
                'status' => true,
                'data' => [
                    'id' => $request->id
                ],
                'message' => 'لقد تم عمليه الحذف بنجاح'
            ]);
        }


    }

    private function getFileUploads($images){
        $image = Upload::whereIn('id',$images)->select('id','url','fileDescription')->get();

        return $image;
    }

}

resources/views/admin/videos/create.blade.php
@extends('admin.layouts.master')
@section('title', __('trans.banks_management'))


@section('styles')
    <style>
        {{--position:relative;--}}
    .progress {  width:100%; height: 30px; border: 1px solid #7F98B2; padding: 1px; border-radius: 3px; }
    .bar { background-color: #B4F5B4; width:0%; height:25px; border-radius: 3px; }
    .percent { position:absolute; display:inline-block; top:3px; left:48%; color: #7F98B2;}
    </style>
@endsection
@section('content')



    <form accept-charset="utf-8" method="POST" action="{{ route('videos.store') }}" enctype="multipart/form-data"
          data-parsley-validate novalidate>
    {{ csrf_field() }}



    <!-- Page-Title -->
        <div class="row">
            <div class="col-lg-12  ">
                <div class="btn-group pull-right m-t-15">
                    {{--  <a href="{{ route('users.create') }}" type="button" class="btn btn-custom waves-effect waves-light"
                        aria-expanded="false"> @lang('maincp.add')
                         <span class="m-l-5">
                         <i class="fa fa-plus"></i>
                     </span>
                     </a> --}}
                </div>
                <h4 class="page-title">  إضافة فيديو  </h4>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12  ">
                <div class="card-box">


{{--                    <h4 class="header-title m-t-0 m-b-30">@lang('trans.add_bank')</h4>--}}

                    <div class="row">

                        <div   class="col-xs-8">

                            <div   class="col-xs-12">
                                <div class="form-group">
                                    <label for="userName">إسم القسم الرئيسي*</label>
                                    <select name="categoryId" id="" class="form-control requiredFieldWithMaxLenght"
                                            required
                                    >
                                        <option value="" selected disabled=""> إختر القسم</option>
                                        @foreach($cats as $value)
                                            <option value="{{ $value->id }}">{{ $value->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="col-xs-12">
                                <div class="form-group">
                                    <label for="userName">إسم الفيديو*</label>
                                    <input type="text" name="name_ar"
                                           class="form-control requiredFieldWithMaxLenght"
                                           required
                                           placeholder="إسم الفيديو..."/>
                                    <p class="help-block" id="error_userName"></p>

                                </div>
                            </div>

                            <div class="col-xs-12">
                                <div class="form-group">
                                    <label for="userName">إسم الفيديو بالإنجليزية*</label>
                                    <input type="text" name="name_en"
                                           class="form-control requiredFieldWithMaxLenght"
                                           required
                                           placeholder="إسم الفديو..."/>
                                    <p class="help-block" id="error_userName"></p>

                                </div>
                            </div>


                            <div class="col-xs-12">
                                <div class="form-group">
                                        <textarea type="text" name="desc_ar" class="form-control m-input  title "
                                                  required
                                                  placeholder="وصف الفيديو بالغة العربية    "   ></textarea>

                                </div>
                            </div>



                            <div class="col-xs-12">
                                <div class="form-group">
                                        <textarea type="text" name="desc_en" class="form-control m-input  title "
                                                  required
                                                  placeholder="وصف الفيديو بالغة الإنجليزية    "   ></textarea>

                                </div>
                            </div>
                        </div>

                        <div class="col-xs-4">
                            <div class="form-group">
                                <label for="usernames">الفيديو *</label>
                                <input type="file" id="myUploader"
                                       accept="video/*"
                                       name="file" class="dropify" />
                                <div class="progress">
                                    <div class="bar"></div >
                                    <div class="percent">0%</div >
                                </div>
                            </div>

                        </div>
                        <!-- end col -->

                        <div class="form-group text-right m-t-20">
                            <button class="btn btn-warning waves-effect waves-light m-t-20 hideButton" value="Submit"   type="submit">
                                @lang('maincp.save_data')
                            </button>
                            <button onclick="window.history.back();return false;" type="reset"
                                    class="btn btn-default waves-effect waves-light m-l-5 m-t-20">
                                @lang('maincp.disable')
                            </button>
                        </div>
                    </div>
                    </div>




                </div>
            </div><!-- end col -->


        </div>
        <!-- end row -->
    </form>

@endsection



@section('scripts')

    {{--<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.js"></script>--}}
    <script src="http://malsup.github.com/jquery.form.js"></script>

    <script type="text/javascript"
            src="{{ request()->root() }}/public/assets/admin/js/validate-{{ config('app.locale') }}.js"></script>


    <script type="text/javascript">



        function validate(formData, jqForm, options) {
            var form = jqForm[0];

            if (!form.file.value) {
                showErrors('{{ session()->get('errors', 'برجاء اختيار فديو التحميل من فضلك  ') }}');
                return false;
            }
        }

        (function() {

            var bar = $('.bar');
            var percent = $('.percent');
            var status = $('#status');

            $('form').ajaxForm({
                beforeSubmit: validate,
                beforeSend: function() {
                    $(".hideButton").hide();
                    status.empty();
                    var percentVal = '0%';
                    var posterValue = $('input[name=file]').fieldValue();
                    bar.width(percentVal)
                    percent.html(percentVal);
                },
                uploadProgress: function(event, position, total, percentComplete) {
                    var percentVal = percentComplete + '%';
                    bar.width(percentVal)
                    percent.html(percentVal);
                    $('.loading').show();
                },
                success: function(data) {
                    var percentVal = 'Wait, Saving';
                    bar.width(percentVal)

                    if (data.status == 422 ){

                        $(".hideButton").show();
                        $('.loading').hide();

                        var shortCutFunction = 'error';
                        var msg = data.message.file;
                        var title = 'خطأ';
                        toastr.options = {
                            positionClass: 'toast-top-center',
                            onclick: null,
                            showMethod: 'slideDown',
                            hideMethod: "slideUp",
                        };
                        var $toast = toastr[shortCutFunction](msg, title); // Wire up an event handler to a button in the toast, if it exists
                        $toastlast = $toast;
                        return false;

                    }
//                    percent.html(percentVal);
//                    window.location.href = data.url;
                },
                complete: function(xhr) {

                    if (xhr.status == 200 && xhr.responseJSON.status == 200 ){

                        status.html(xhr.responseText);
                        showMessage('{{ session()->get('success', 'تم الرفع بنجاح') }}');
                        $(".hideButton").show();
                        $('.loading').hide();

                    }

                },error:function (error) {
                    $('.loading').hide();
                    $(".hideButton").show();
                    showErrors('{{ session()->get('errors', 'حدث خطا اثناء الرفع ') }}');

//                    setTimeout(function () {
//                     location.reload();
//                    }, 1000);
                }
            });

        })();
    </script>
@endsection

resources/views/admin/videos/show.blade.php
@extends('admin.layouts.master')
@section('title', 'تفاصيل الفديو')
@section('content')





    <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12">
                <div class="btn-group pull-right m-t-15">
                    {{--<button type="button" class="btn btn-custom  waves-effect waves-light"--}}
                        {{--onclick="window.history.back();return false;"> @lang('maincp.back') <span class="m-l-5"><i--}}
                                {{--class="fa fa-reply"></i></span>--}}
                    {{--</button>--}}

                    <a href="{{ route('videos.index') }}"
                       class="btn btn-custom  waves-effect waves-light">
												<span><span>رجوع  </span>
													<i class="fa fa-reply"></i>
												</span>
                    </a>

                </div>
                <h4 class="page-title">بيانات الفديو </h4>
            </div>
        </div>


        <div class="row">


                <div class="col-sm-12">

                <div class="card-box">
                    <div class="row">

                        <div class="col-lg-12">
                            <div class="card-box p-b-0">


                                <h4 class="header-title m-t-0 m-b-30">التفاصيل</h4>

                                <form>
                                    <div id="basicwizard" class=" pull-in">
                                        <ul class="nav nav-tabs navtab-wizard nav-justified bg-muted">
                                            <li class="active"><a href="#tab1" onclick="pauseVid()" data-toggle="tab" aria-expanded="false">البيانات الاساسية</a></li>
                                            <li class=""><a href="#tab2" data-toggle="tab" aria-expanded="true"> الفيديو </a></li>
                                        </ul>
                                        <div class="tab-content b-0 m-b-0">
                                            <div class="tab-pane m-t-10 fade active in" id="tab1">
                                                <div class="row">
                                                    <div class="col-sm-8">
                                                        <div class="col-xs-12 col-lg-12">

                                                            <hr>
                                                        </div>

                                                        <div class="col-lg-12 col-xs-12 col-md-12 col-sm-12">
                                                            <label> إسم الفديو :</label>
                                                            <input class="form-control" value="{{ $video->name }}"><br>
                                                        </div>

                                                        @if($video->description )
                                                            <div class="col-lg-12 col-xs-12 col-md-12 col-sm-12" style="margin: 10px auto">
                                                                <label> تفاصيل الفديو  :</label>
                                                                <textarea class="form-control">{{ $video->description }}</textarea>
                                                            </div>
                                                        @endif



                                                        @if($video->category )
                                                            <div class="col-lg-12 col-xs-12 col-md-12 col-sm-12">
                                                                <label>القسم التابع لهذا الفديو  :</label>
                                                                <input class="form-control" value="{{ optional($video->category)->name  }}"><br>
                                                            </div>
                                                        @endif




                                                    </div>

                                                </div>

                                            </div>
                                            <div class="tab-pane m-t-10 fade " id="tab2">

                                                @if( $video->uploads)
                                                    <div class="form-group">

                                                    @if(count($video->uploads) > 0)

                                                        @foreach($video->uploads as $item)


                                                            <div class="col-lg-12">

                                                                <video id="videoPlayer" width="100%" height="50%" controls>
                                                                    <source src="{{$item['url']}}" type="video/mp4">
                                                                </video>
                                                                {{--<iframe width="420" height="315" src="{{$item['url']}}" frameborder="0" allowfullscreen></iframe>--}}

                                                                {{--<a data-fancybox="gallery">--}}

                                                                   {{--href="{{ $helper->getDefaultImage($item->url, request()->root().'/public/assets/admin/custom/images/default.png') }}">--}}
                                                                    {{--<img style="width: 100% ; height: 100%" src="{{ $helper->getDefaultImage($item->url, request()->root().'/public/assets/admin/custom/images/default.png') }}"/>--}}
                                                               {{----}}
                                                                {{--</a>--}}
                                                            </div>
                                                        @endforeach
                                                    @endif
                                                    </div>
                                                @else
                                                        لا يوجد اي صور لهذا الإعلان
                                                @endif

                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>



                    </div>
                </div>
            </div>

        </div>




@endsection




@section('scripts')
    <script type="text/javascript">

        var videoplayer = document.getElementById("videoPlayer");

        function pauseVid() {
            videoplayer.pause();
        }


    </script>


@endsection