routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/', 'HomeController@index')->name('home');

Route::group(['prefix' => 'administrator'], function () {


    Route::get('/login', 'Admin\LoginController@login')->name('admin.login');
    Route::post('/login', 'Admin\LoginController@postLogin')->name('admin.postLogin');

    // Password Reset Routes...

    Route::get('password/reset', 'Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('administrator.password.request');
    Route::post('password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('administrator.password.email');
    Route::get('password/reset/{token}', 'Admin\Auth\ResetPasswordController@showResetForm')->name('administrator.password.reset.token');
    Route::post('password/reset', 'Admin\Auth\ResetPasswordController@reset');

});

Route::group(['prefix' => 'administrator', 'middleware' => ['admin']], function () {

    Route::get('/', 'Admin\HomeController@index')->name('home');
    Route::get('/home', 'Admin\HomeController@index')->name('admin.home');


    // administrators --- Admin Panel users
    // add admin or some one who controll Or help for admin panel

    Route::resource('helpAdmin', 'Admin\HelpAdminController');
    Route::get('helpAdmin/{id}/delete', 'Admin\HelpAdminController@delete')->name('helpAdmin.delete');
    Route::post('helpAdmin/{id}/delete', 'Admin\HelpAdminController@deleteHelpAdmin')->name('helpAdmin.message.delete');
    Route::post('helpAdmin/{id}/suspend', 'Admin\HelpAdminController@suspendHelpAdmin')->name('helpAdmin.message.suspend');
    Route::get('user/{id}/delete', 'Admin\UsersController@delete')->name('user.for.delete');
    Route::post('user/suspend', 'Admin\HelpAdminController@suspend')->name('user.suspend');
    // Roles routes ..........
    Route::resource('roles', 'Admin\RolesController');
    Route::post('role/delete', 'Admin\RolesController@delete')->name('role.delete');


    Route::resource('users', 'Admin\UsersController');
    Route::post('accepted','Admin\UsersController@accpetedUser')->name('user.accepted');

    Route::get('settings/aboutus', 'Admin\SettingsController@aboutus')->name('settings.aboutus');
    Route::get('settings/taxs', 'Admin\SettingsController@taxs')->name('settings.taxs');
    Route::get('settings/terms', 'Admin\SettingsController@terms')->name('settings.terms');
    Route::get('settings/suspendElement', 'Admin\SettingsController@suspendElement')->name('settings.suspendElement');


    Route::get('/settings/app-general-settings', 'Admin\SettingsController@appGeneralSettings')->name('settings.app.general');
    Route::get('settings/contacts', 'Admin\SettingsController@contactus')->name('settings.contactus');


    Route::post('/settings', 'Admin\SettingsController@store')->name('administrator.settings.store');

    Route::post('contactus/reply/{id}', 'Admin\SupportsController@reply')->name('support.reply');
    Route::get('contactus', 'Admin\SupportsController@index')->name('support.index');
    Route::get('contactus/{id}', 'Admin\SupportsController@show')->name('support.show');
    Route::post('support/contact/delete', 'Admin\SupportsController@delete')->name('support.contact.delete');


    Route::resource('supports', 'Admin\SupportsController');
    Route::post('supports/delete', 'Admin\SupportsController@delete')->name('supports.delete');

    Route::resource('types', 'Admin\TypesSupportController');




    // -------------------------------------- categories .................
    Route::resource('categories', 'Admin\CategoriesController');
    Route::post('categories/delete', 'Admin\CategoriesController@delete')->name('categories.delete');
    Route::post('categories/suspend', 'Admin\CategoriesController@suspend')->name('categories.suspend');




    Route::resource('banks', 'Admin\BanksController');
    Route::post('bank/suspend', 'Admin\BanksController@suspend')->name('bank.suspend');



    Route::resource('videos', 'Admin\VideoController');
    Route::post('videos/suspend', 'Admin\VideoController@suspend')->name('videos.suspend');
    Route::post('videos/delete', 'Admin\VideoController@delete')->name('videos.delete');

    Route::post('/logout', 'Admin\LoginController@logout')->name('administrator.logout');

});

app/Models/TypesSupport.php
<?php

namespace App\Models;

use Dimsav\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;

class TypesSupport extends Model
{
       use Translatable;
       public $translatedAttributes = ['name'];
       protected $fillable = ['name'];
       
       public function support()
       {
	    return $this->belongsTo(Support::class);
       }
}

resources/views/admin/types_support/create.blade.php
@extends('admin.layouts.master')
@section('styles')
    <style>
        .help-block {
            color: #ff5b5b !important;
            font-size: 16px !important;
        }
        .validation_style {
            border: 1px solid red !important;
        }
    </style>
@endsection
@section('content')
    <div class="m-grid__item m-grid__item--fluid m-wrapper">

        <div class="m-content">

            <div class="row">
                <div class="col-lg-12">

                    <!--begin::Portlet-->
                    <div class="m-portlet">

                        <div class="m-portlet__head">

                            <div class="m-portlet__head-caption">
                                <div class="m-portlet__head-title">

                                    <span class="m-portlet__head-icon m--hide">
                                        <i class="la la-gear"></i>
                                    </span>
                                    <h3 class="m-portlet__head-text">
                                          إضافة المدينة
                                    </h3>

                                </div>

                            </div>
                            <div class="m-portlet__head-tools">
                                <ul class="m-portlet__nav">
                                    <li class="m-portlet__nav-item">
                                        <a href="#"  onclick="window.history.back();return false;"
                                           class="btn btn-metal">
												<span>
													<i class="la la-backward"></i>
													<span>رجوع  </span>
												</span>
                                        </a>
                                    </li>

                                </ul>
                            </div>

                        </div>

                        <form method="POST" action="{{ route('cities.store')  }}" enctype="multipart/form-data" data-parsley-validate
                              novalidate>
                            {{ csrf_field() }}

                            <div class="m-portlet__body">
                                <div class="m-form__section m-form__section--first">

                                    <div class="m-form__heading">
                                        <h3 class="m-form__heading-title">المدينة:</h3>
                                    </div>

                                    <div class="form-group m-form__group row{{ $errors->has('name_ar') ? ' has-error' : '' }}">
                                        <label class="col-lg-2 col-form-label"> الاسم المدينة_باللغة العربية  *:</label>
                                        <div class="col-lg-8">
                                            <input type="text" name="name_ar" class="form-control m-input nameValid"
                                                   required
                                                   placeholder="إدخل اسم المدينة باللغة العربية   "   >
                                        </div>
                                        @if($errors->has('name_ar'))
                                            <p class="help-block">
                                                {{ $errors->first('name_ar') }}
                                            </p>
                                        @endif
                                    </div>


                                </div>


                            </div>

                            <div class="m-portlet__foot m-portlet__foot--fit">
                                <div class="m-form__actions m-form__actions">
                                    <div class="row">
                                        <div class="col-lg-2"></div>
                                        <div class="col-lg-6">
                                            <button type="submit" class="btn btn-primary" id="m_blockui_3_1">إضافة </button>
                                            <a href="{{route('cities.index')}}" type="reset" class="btn btn-secondary">الغاء</a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </form>

                        <!--end::Form-->
                    </div>

                </div>
            </div>
        </div>

    </div>
@endsection

resources/views/admin/types_support/edit.blade.php
@extends('admin.layouts.master')

@section('title','الشكوي')

@section('styles')
    <style>
        .help-block {
            color: #ff5b5b !important;
            font-size: 16px !important;
        }
        .validation_style {
            border: 1px solid red !important;
        }
    </style>
@endsection
@section('content')

    <div class="m-grid__item m-grid__item--fluid m-wrapper">

        <div class="m-content">

            <div class="row">
                <div class="col-lg-12">

                    <!--begin::Portlet-->
                    <div class="m-portlet">

                        <div class="m-portlet__head">

                            <div class="m-portlet__head-caption">
                                <div class="m-portlet__head-title">

                                    <span class="m-portlet__head-icon m--hide">
                                        <i class="la la-gear"></i>
                                    </span>
                                    <h3 class="m-portlet__head-text">
                                        تعديل الشكوي
                                    </h3>

                                </div>

                            </div>
                            <div class="m-portlet__head-tools">
                                <ul class="m-portlet__nav">
                                    <li class="m-portlet__nav-item">
                                        <a href="{{route('types.index')}}"
                                           class="btn btn-metal">
												<span>
													<i class="la la-backward"></i>
													<span>رجوع  </span>
												</span>
                                        </a>
                                    </li>

                                </ul>
                            </div>

                        </div>

                        <form method="POST" action="{{ route('types.update', $type->id) }}" enctype="multipart/form-data"
                              data-parsley-validate novalidate>

                            {{ csrf_field() }}
                            {{ method_field('PUT') }}

                            <div class="m-portlet__body">
                                <div class="m-form__section m-form__section--first">

                                    <div class="m-form__heading">
                                        <h3 class="m-form__heading-title">الشكوي :</h3>
                                    </div>

                                    <div class="form-group m-form__group row{{ $errors->has('name_ar') ? ' has-error' : '' }}">
                                        <label class="col-lg-2 col-form-label">اسم الرسالة  *:</label>
                                        <div class="col-lg-8">
                                            <input type="text" name="name_ar"
                                                        class="form-control m-input nameValid"
                                                        value=" {{ $type->name }}"
                                                   required
                                                   placeholder="إدخل اسم المدينة باللغة العربية   "   >
                                        </div>
                                        @if($errors->has('name_ar'))
                                            <p class="help-block">
                                                {{ $errors->first('name_ar') }}
                                            </p>
                                        @endif
                                    </div>

                            </div>
                            <div class="m-portlet__foot m-portlet__foot--fit">
                                <div class="m-form__actions m-form__actions">
                                    <div class="row">
                                        <div class="col-lg-2"></div>
                                        <div class="col-lg-6">
                                            <button type="submit" class="btn btn-primary" id="m_blockui_3_1">تعديل </button>
                                            <a href="{{route('types.index')}}" type="reset" class="btn btn-secondary">الغاء</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>



                        <!--end::Form-->
                    </div>

                </div>
            </div>
        </div>

    </div>

@endsection

resources/views/admin/types_support/index.blade.php
@extends('admin.layouts.master')

@section('title', __('maincp.call_us'))

@section('content')

    <!-- Page-Title -->
    <div class="row">
        <div class="col-sm-12">
            <div class="btn-group pull-right m-t-15">

                <a href="{{ route('support.index') }}"
                   style="margin: 0 15px"
                   class="btn btn-success ">
                    رجوع إلي رسائل تواصل معنا
                </a>


            </div>

            <h4 class="page-title">@lang('maincp.call_us')</h4>
        </div>
    </div>


    <div class="row">
        <div class="col-lg-12">
            <div class="card-box">

                <div class="dropdown pull-right">
                </div>

                <h4 class="header-title m-t-0 m-b-30">نوع الرسالة</h4>

                <table class="table m-0  table-striped table-hover table-condensed" id="datatable-fixed-header">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>إسم الرسالة</th>
                        <th>  الخيارات</th>
                    </tr>
                    </thead>
                    <tbody>
                    @php $i = 1; @endphp
                    @foreach($types as $type)
                        <tr>
                            <td>{{$i++}}</td>
                            <td>{{ $type->name }} </td>
                            <td>
                                <button class="btn btn-sm btn-success" data-toggle="modal" data-target="#con-close-modal{{$type->id}}">  <i class="fa fa-pencil"></i></button>
                                <div id="con-close-modal{{$type->id}}" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                                <h4 class="modal-title">    تعديل نوع الرسالة   </h4>
                                            </div>
                                            <form method="POST" action="{{ route('types.update', $type->id) }}" >
                                                {{ csrf_field() }}
                                                {{ method_field('PUT') }}
                                                <div class="modal-body">
                                                    <div class="row">
                                                        <div class="col-md-12">
                                                            <div class="form-group no-margin">
                                                                <label   class="control-label">تعديل :</label>
                                                                <input type="text" class="  form-control" name="name_ar" value="{{$type->name}}">
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">إلغاء</button>
                                                    <button type="submit" class="btn btn-info waves-effect waves-light">حفظ  </button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div><!-- /.modal -->

                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>




                {{--<div class="articles">--}}

                {{--                    @include('admin.categories.load')--}}

                {{--</div>--}}
            </div>
        </div><!-- end col -->

    </div>
    <!-- end row -->



@endsection


@section('scripts')


    <script>






        $('body').on('click', '.removeElement', function () {
            var id = $(this).attr('data-id');
            var $tr = $(this).closest($('#elementRow' + id).parent().parent());
            var $url = $(this).attr('data-url');

            swal({
                title: "هل انت متأكد؟",
                text: "يمكنك استرجاع المحذوفات مرة اخرى لا تقلق.",
                type: "error",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "موافق",
                cancelButtonText: "إلغاء",
                confirmButtonClass: 'btn-danger waves-effect waves-light',
                closeOnConfirm: true,
                closeOnCancel: true,
            }, function (isConfirm) {
                if (isConfirm) {
                    $.ajax({
                        type: 'POST',
                        url: $url,
                        data: {id: id},
                        dataType: 'json',
                        success: function (data) {
                            if (data) {
                                var shortCutFunction = 'success';
                                var msg = 'لقد تمت عملية الحذف بنجاح.';
                                var title = data.title;
                                toastr.options = {
                                    positionClass: 'toast-top-center',
                                    onclick: null,
                                    showMethod: 'slideDown',
                                    hideMethod: "slideUp",
                                };
                                var $toast = toastr[shortCutFunction](msg, title); // Wire up an event handler to a button in the toast, if it exists
                                $toastlast = $toast;
                            }

                            $tr.find('td').fadeOut(1000, function () {
                                $tr.remove();
                            });
                        }
                    });
                } else {

                    swal({
                        title: "تم الالغاء",
                        text: "انت لغيت عملية الحذف تقدر تحاول فى اى وقت :)",
                        type: "error",
                        showCancelButton: false,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "موافق",
                        confirmButtonClass: 'btn-info waves-effect waves-light',
                        closeOnConfirm: false,
                        closeOnCancel: false

                    });

                }
            });
        });

    </script>



@endsection

resources/views/admin/types_support/show.blade.php
@extends('admin.layouts.master')
@section('title','تفاصيل المدينة')

@section('content')
    <div class="row">
        <p>عرض تفاصيل المدينة رقم {{$id}}</p>
    </div>

@endsection